"""JSON Path node generated by aotn_node_helper."""

from typing import Any, ClassVar, Dict, List

from ...node_base import Node, NodeContext
from ...node_category import NodeCategory


class JsonPathNode(Node):
    """Extract a value from a JSON string by dot-path (e.g. "user.name")."""

    node_type: ClassVar[str] = 'json_path_node'
    display_name: ClassVar[str] = 'JSON Path'
    default_alias: ClassVar[str] = 'JSON Path'
    description: ClassVar[str] = 'Extract a value from a JSON string by dot-path (e.g. "user.name")'
    category: ClassVar[str] = NodeCategory.DATA
    primary_family: ClassVar[str] = 'Complex'
    tags: ClassVar[List[str]] = ['Utility']
    icon_name: ClassVar[str] = 'braces'
    color_hint: ClassVar[str] = 'violet'
    input_ports: ClassVar[List[str]] = ['input']
    output_ports: ClassVar[List[str]] = ['default', 'error']
    input_port_metadata: ClassVar[Dict[str, Dict[str, str]]] = {}
    output_port_metadata: ClassVar[Dict[str, Dict[str, str]]] = {}
    default_config: ClassVar[Dict[str, Any]] = {'path': '', 'default_value': ''}
    config_schema: ClassVar[Dict[str, Dict[str, Any]]] = {'path': {'type': 'string', 'label': 'Dot path', 'placeholder': 'user.name', 'required': True, 'tab': 'Parameters'}, 'default_value': {'type': 'string', 'label': 'Default on miss', 'required': False, 'tab': 'Parameters'}}
    ui_hints: ClassVar[Dict[str, Any]] = {}

    async def execute(self, context: NodeContext) -> None:
        import json

        raw = context.inputs.get("input", "")
        path = str(self.config.get("path") or "").strip()
        default_value = self.config.get("default_value", "")

        try:
            data = json.loads(raw) if isinstance(raw, str) else raw
        except (json.JSONDecodeError, TypeError) as exc:
            context.signal_done({"data": {"error": f"Invalid JSON: {exc}"}})
            return

        result = data
        for segment in path.split("."):
            if not segment:
                continue
            if isinstance(result, dict):
                if segment not in result:
                    result = default_value
                    break
                result = result[segment]
            elif isinstance(result, list):
                try:
                    result = result[int(segment)]
                except (ValueError, IndexError):
                    result = default_value
                    break
            else:
                result = default_value
                break

        context.signal_done({"data": {"default": result}})
