"""Random Number node generated by aotn_node_helper."""

from typing import Any, ClassVar, Dict, List

from ...node_base import Node, NodeContext
from ...node_category import NodeCategory


class RandomNumberNode(Node):
    """Produce a random integer or float within a configured range."""

    node_type: ClassVar[str] = 'random_number_node'
    display_name: ClassVar[str] = 'Random Number'
    default_alias: ClassVar[str] = 'Random Number'
    description: ClassVar[str] = 'Produce a random integer or float within a configured range'
    category: ClassVar[str] = NodeCategory.DATA
    primary_family: ClassVar[str] = 'Complex'
    tags: ClassVar[List[str]] = ['Utility']
    icon_name: ClassVar[str] = 'dice-3'
    color_hint: ClassVar[str] = 'violet'
    input_ports: ClassVar[List[str]] = ['input']
    output_ports: ClassVar[List[str]] = ['default']
    input_port_metadata: ClassVar[Dict[str, Dict[str, str]]] = {}
    output_port_metadata: ClassVar[Dict[str, Dict[str, str]]] = {}
    default_config: ClassVar[Dict[str, Any]] = {'mode': 'integer', 'min_value': 0, 'max_value': 100, 'seed': '', 'value': ''}
    config_schema: ClassVar[Dict[str, Dict[str, Any]]] = {'mode': {'type': 'select', 'label': 'Mode', 'options': ['integer', 'float'], 'tab': 'Parameters'}, 'min_value': {'type': 'float', 'label': 'Minimum value', 'required': False, 'tab': 'Parameters'}, 'max_value': {'type': 'float', 'label': 'Maximum value', 'required': False, 'tab': 'Parameters'}, 'seed': {'type': 'string', 'label': 'Random seed (blank = unseeded)', 'required': False, 'tab': 'Parameters'}, 'value': {'type': 'string', 'label': 'Payload', 'required': False}}
    ui_hints: ClassVar[Dict[str, Any]] = {}

    async def execute(self, context: NodeContext) -> None:
        import random

        mode = str(self.config.get("mode") or "integer")
        min_val = float(self.config.get("min_value") if self.config.get("min_value") is not None else 0)
        max_val = float(self.config.get("max_value") if self.config.get("max_value") is not None else 100)
        seed_raw = str(self.config.get("seed") or "").strip()

        rng = random.Random(seed_raw) if seed_raw else random.Random()

        if mode == "float":
            result = rng.uniform(min_val, max_val)
        else:
            result = rng.randint(int(min_val), int(max_val))

        context.signal_done({"data": {"default": result}})
