"""Text Transform node generated by aotn_node_helper.

The `markdown format` operation (FO2, docs/FILE_OUTPUT_BUILD_PLAN.md) tidies
text for human reading via backend.text_format.format_markdown — a pure
transform kept out of file_output_node so formatting stays composable.
"""

from typing import Any, ClassVar, Dict, List

from ...node_base import Node, NodeContext
from ...node_category import NodeCategory
from ...text_format import format_markdown


class TextTransformNode(Node):
    """Apply a text transformation (case, strip, reverse, markdown format) to the input string."""

    node_type: ClassVar[str] = 'text_transform_node'
    display_name: ClassVar[str] = 'Text Transform'
    default_alias: ClassVar[str] = 'Text Transform'
    description: ClassVar[str] = 'Apply a text transformation (case, strip, reverse, markdown format) to the input string'
    category: ClassVar[str] = NodeCategory.DATA
    primary_family: ClassVar[str] = 'Complex'
    tags: ClassVar[List[str]] = ['Utility']
    icon_name: ClassVar[str] = 'case-sensitive'
    color_hint: ClassVar[str] = 'violet'
    input_ports: ClassVar[List[str]] = ['input']
    output_ports: ClassVar[List[str]] = ['default']
    input_port_metadata: ClassVar[Dict[str, Dict[str, str]]] = {}
    output_port_metadata: ClassVar[Dict[str, Dict[str, str]]] = {}
    default_config: ClassVar[Dict[str, Any]] = {'operation': 'uppercase', 'wrap_width': 0}
    config_schema: ClassVar[Dict[str, Dict[str, Any]]] = {
        'operation': {
            'type': 'select',
            'label': 'Operation',
            'options': ['uppercase', 'lowercase', 'strip', 'title', 'reverse', 'markdown format'],
            'tab': 'Parameters',
        },
        'wrap_width': {
            'type': 'integer',
            'label': 'Wrap width',
            'description': 'Re-flow paragraphs to this width; 0 keeps existing line breaks',
            'min': 0,
            'tab': 'Parameters',
            'visible_when': {'operation': 'markdown format'},
        },
    }
    ui_hints: ClassVar[Dict[str, Any]] = {}

    async def execute(self, context: NodeContext) -> None:
        value = str(context.inputs.get("input") or "")
        operation = str(self.config.get("operation") or "uppercase")
        try:
            wrap_width = max(0, int(self.config.get("wrap_width") or 0))
        except (TypeError, ValueError):
            wrap_width = 0
        ops = {
            "uppercase": str.upper,
            "lowercase": str.lower,
            "strip": str.strip,
            "title": str.title,
            "reverse": lambda s: s[::-1],
            "markdown format": lambda s: format_markdown(s, wrap_width),
        }
        transform = ops.get(operation, str.upper)
        context.signal_done({"data": {"default": transform(value)}})
