"""Text Transform node generated by aotn_node_helper."""

from typing import Any, ClassVar, Dict, List

from ...node_base import Node, NodeContext
from ...node_category import NodeCategory


class TextTransformNode(Node):
    """Apply a text transformation (uppercase, lowercase, strip, title, reverse) to the input string."""

    node_type: ClassVar[str] = 'text_transform_node'
    display_name: ClassVar[str] = 'Text Transform'
    default_alias: ClassVar[str] = 'Text Transform'
    description: ClassVar[str] = 'Apply a text transformation (uppercase, lowercase, strip, title, reverse) to the input string'
    category: ClassVar[str] = NodeCategory.DATA
    primary_family: ClassVar[str] = 'Complex'
    tags: ClassVar[List[str]] = ['Utility']
    icon_name: ClassVar[str] = 'case-sensitive'
    color_hint: ClassVar[str] = 'violet'
    input_ports: ClassVar[List[str]] = ['input']
    output_ports: ClassVar[List[str]] = ['default']
    input_port_metadata: ClassVar[Dict[str, Dict[str, str]]] = {}
    output_port_metadata: ClassVar[Dict[str, Dict[str, str]]] = {}
    default_config: ClassVar[Dict[str, Any]] = {'operation': 'uppercase'}
    config_schema: ClassVar[Dict[str, Dict[str, Any]]] = {'operation': {'type': 'select', 'label': 'Operation', 'options': ['uppercase', 'lowercase', 'strip', 'title', 'reverse'], 'tab': 'Parameters'}}
    ui_hints: ClassVar[Dict[str, Any]] = {}

    async def execute(self, context: NodeContext) -> None:
        value = str(context.inputs.get("input") or "")
        operation = str(self.config.get("operation") or "uppercase")
        ops = {
            "uppercase": str.upper,
            "lowercase": str.lower,
            "strip": str.strip,
            "title": str.title,
            "reverse": lambda s: s[::-1],
        }
        transform = ops.get(operation, str.upper)
        context.signal_done({"data": {"default": transform(value)}})
