"""File Instance node generated by aotn_node_helper."""

from typing import Any, ClassVar, Dict, List, Optional

from ...node_base import Node, NodeContext
from ...node_category import NodeCategory


class ExampleFileInstanceNode(Node):
    """Opens a file at a configured or supplied path and reports success."""

    node_type: ClassVar[str] = 'example_file_instance_node'
    display_name: ClassVar[str] = 'File Instance'
    default_alias: ClassVar[str] = 'File Instance'
    description: ClassVar[str] = 'Opens a file at a configured or supplied path and reports success'
    category: ClassVar[str] = NodeCategory.IO
    primary_family: ClassVar[str] = 'Inputs'
    tags: ClassVar[List[str]] = ['File I/O', 'Runtime Resource']
    icon_name: ClassVar[str] = 'file-input'
    color_hint: ClassVar[str] = 'green'
    group: ClassVar[Optional[str]] = None
    selector_section: ClassVar[Optional[str]] = None
    input_ports: ClassVar[List[str]] = ['file_path']
    output_ports: ClassVar[List[str]] = ['default']
    input_port_metadata: ClassVar[Dict[str, Dict[str, Any]]] = {'file_path': {'name': 'File Path', 'description': 'Where the file path comes from at execution time', 'data_type': 'file', 'required': False, 'sources': ['upstream', 'vault', 'configured']}}
    output_port_metadata: ClassVar[Dict[str, Dict[str, Any]]] = {'default': {'name': 'Open Result', 'description': 'True when the file opened successfully, false on error', 'data_type': 'bool', 'required': True, 'to': ['downstream', 'vault'], 'pass_through': True}}
    default_config: ClassVar[Dict[str, Any]] = {'file_path_source': 'Configured', 'file_path_vault_key': '', 'file_path': '', 'transient_output': True, 'dead_drop_passthrough': False, 'vault_write': False, 'vault_write_key': ''}
    config_schema: ClassVar[Dict[str, Dict[str, Any]]] = {'file_path_source': {'type': 'select', 'label': 'File path source', 'options': ['Upstream payload', 'Vault', 'Configured'], 'tab': 'Source', 'description': 'Where the file path comes from at execution time'}, 'file_path_vault_key': {'type': 'string', 'label': 'File path Vault key', 'required': False, 'tab': 'Source', 'enabled_when': {'file_path_source': 'Vault'}}, 'file_path': {'type': 'string', 'label': 'File path', 'placeholder': '/path/to/file', 'tab': 'Parameters', 'enabled_when': {'file_path_source': 'Configured'}}, 'transient_output': {'type': 'boolean', 'label': 'Send bool result to next node', 'tab': 'Payloads', 'mutually_exclusive_with': ['dead_drop_passthrough']}, 'dead_drop_passthrough': {'type': 'boolean', 'label': 'Forward incoming payload unchanged', 'tab': 'Payloads', 'mutually_exclusive_with': ['transient_output']}, 'vault_write': {'type': 'boolean', 'label': 'Save error message to Vault', 'tab': 'Payloads'}, 'vault_write_key': {'type': 'string', 'label': 'Error log Vault key', 'required': False, 'tab': 'Payloads', 'enabled_when': {'vault_write': True}}}
    ui_hints: ClassVar[Dict[str, Any]] = {}

    async def execute(self, context: NodeContext) -> None:
        value = context.inputs.get("input", "")
        context.signal_done({"data": {'default': value}})
