"""HTTP Request node generated by aotn_node_helper."""

from typing import Any, ClassVar, Dict, List

from ...node_base import Node, NodeContext
from ...node_category import NodeCategory


class HttpRequestNode(Node):
    """Make an HTTP GET or POST request and forward the response body."""

    node_type: ClassVar[str] = 'http_request_node'
    display_name: ClassVar[str] = 'HTTP Request'
    default_alias: ClassVar[str] = 'HTTP Request'
    description: ClassVar[str] = 'Make an HTTP GET or POST request and forward the response body'
    category: ClassVar[str] = NodeCategory.IO
    primary_family: ClassVar[str] = 'Inputs'
    tags: ClassVar[List[str]] = ['Internet']
    icon_name: ClassVar[str] = 'globe'
    color_hint: ClassVar[str] = 'green'
    input_ports: ClassVar[List[str]] = ['input']
    output_ports: ClassVar[List[str]] = ['default', 'error']
    input_port_metadata: ClassVar[Dict[str, Dict[str, str]]] = {}
    output_port_metadata: ClassVar[Dict[str, Dict[str, str]]] = {}
    default_config: ClassVar[Dict[str, Any]] = {'url': '', 'method': 'GET', 'body': '', 'timeout_seconds': 10.0, 'auth_token_secret': ''}
    config_schema: ClassVar[Dict[str, Dict[str, Any]]] = {'url': {'type': 'string', 'label': 'URL', 'placeholder': 'https://example.com/api', 'required': True, 'tab': 'Parameters'}, 'method': {'type': 'select', 'label': 'Method', 'options': ['GET', 'POST'], 'tab': 'Parameters'}, 'body': {'type': 'multiline', 'label': 'Request body (POST)', 'required': False, 'tab': 'Parameters'}, 'timeout_seconds': {'type': 'float', 'label': 'Timeout (seconds)', 'required': False, 'tab': 'Parameters'}, 'auth_token_secret': {'type': 'string', 'label': 'Bearer token (secrets store key)', 'secret': True, 'required': False, 'tab': 'Parameters'}}
    ui_hints: ClassVar[Dict[str, Any]] = {}

    async def execute(self, context: NodeContext) -> None:
        import urllib.error
        import urllib.request

        url = str(self.config.get("url") or "").strip()
        if not url:
            context.signal_done({"data": {"error": "URL is required"}})
            return

        method = str(self.config.get("method") or "GET").upper()
        body_text = str(self.config.get("body") or "")
        timeout = float(self.config.get("timeout_seconds") or 10.0)

        try:
            body_bytes = body_text.encode("utf-8") if method == "POST" and body_text else None
            req = urllib.request.Request(url, data=body_bytes, method=method)
            token_key = str(self.config.get("auth_token_secret") or "").strip()
            if token_key:
                token = context.get_secret(token_key)
                if token:
                    req.add_header("Authorization", f"Bearer {token}")
            with urllib.request.urlopen(req, timeout=timeout) as response:
                charset = "utf-8"
                content_type = response.headers.get("Content-Type", "")
                if "charset=" in content_type:
                    charset = content_type.split("charset=")[-1].split(";")[0].strip()
                result = response.read().decode(charset, errors="replace")
            context.signal_done({"data": {"default": result}})
        except urllib.error.URLError as exc:
            context.signal_done({"data": {"error": str(exc)}})
